name: "Setup {reticulate} environment"

description: "Sets up Python and Reticulate virtual environment for R projects."
inputs:
  python-version:
    description: "Python version to install"
    required: true
    default: "3.12.x"
    
outputs:
  reticulate-python:
    description: "Path to the Reticulate Python environment"

runs:
  using: "composite"
  steps:
    - name: Install system dependencies (Ubuntu only)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-venv

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Setup venv with {Reticulate}
      shell: Rscript {0}
      env:
        PYTHON_VERSION: ${{ inputs.python-version }}
      run: |
        
        path_to_python <- reticulate::virtualenv_create(
          envname = "r-reticulate",
          python = reticulate::virtualenv_starter(  Sys.getenv("PYTHON_VERSION") ),
          version =   Sys.getenv("PYTHON_VERSION"),
          packages = c(
            "numpy",
            "scipy",
            "torch",
            "torchmetrics",
            "scikit-learn",
            "imblearn"
          )
        )

        writeLines(
          sprintf("RETICULATE_PYTHON=%s", path_to_python),
          Sys.getenv("GITHUB_ENV")
        )
