project:
  type: book
book:
  title: '{SLmetrics}: Machine Learning Performance Evaluation on Steroids'
  subtitle: Version 0.3-1
  author: Serkan Korkmaz
  version: 0.3-1
  repo-url: https://github.com/serkor1/SLmetrics
  repo-branch: development
  repo-subdir: docs
  repo-actions:
  - edit
  - source
  - issue
  sharing:
  - twitter
  - facebook
  - linkedin
  sidebar:
    title: Documentation
  chapters:
  - index.qmd
  - intro.qmd
  - summary.qmd
  - benchmark.qmd
  - part: functions.qmd
    chapters:
    - references/accuracy.qmd
    - references/baccuracy.qmd
    - references/ccc.qmd
    - references/ckappa.qmd
    - references/cmatrix.qmd
    - references/dor.qmd
    - references/entropy.qmd
    - references/fbeta.qmd
    - references/fdr.qmd
    - references/fer.qmd
    number-sections: false
  - references.qmd
bibliography: references.bib
format:
  html:
    theme:
      light:
      - cosmo
      - theme-light.scss
      dark:
      - darkly
      - theme-dark.scss
  pdf:
    documentclass: scrreprt
execute:
  freeze: auto
  cache: true
