project:
  type: book
book:
  title: '{SLmetrics}: Machine Learning Performance Evaluation on Steroids'
  subtitle: Version 0.3-1
  author: Serkan Korkmaz
  version: 0.3-1
  repo-url: https://github.com/serkor1/SLmetrics
  repo-branch: development
  repo-subdir: docs
  repo-actions:
  - edit
  - source
  - issue
  sharing:
  - twitter
  - facebook
  - linkedin
  sidebar:
    title: Documentation
  chapters:
  - index.qmd
  - intro.qmd
  - summary.qmd
  - benchmark.qmd
  - part: functions.qmd
    chapters:
    - references/ROC.qmd
    - references/accuracy.qmd
    - references/baccuracy.qmd
    - references/ccc.qmd
    - references/ckappa.qmd
    - references/cmatrix.qmd
    - references/dor.qmd
    - references/entropy.qmd
    - references/fbeta.qmd
    - references/fdr.qmd
    - references/fer.qmd
    - references/fmi.qmd
    - references/fpr.qmd
    - references/huberloss.qmd
    - references/jaccard.qmd
    - references/logloss.qmd
    - references/mae.qmd
    - references/mape.qmd
    - references/mcc.qmd
    - references/mpe.qmd
    - references/mse.qmd
    - references/nlr.qmd
    - references/npv.qmd
    - references/pinball.qmd
    - references/plr.qmd
    - references/prROC.qmd
    - references/precision.qmd
    - references/rae.qmd
    - references/recall.qmd
    - references/rmse.qmd
    - references/rmsle.qmd
    - references/rrmse.qmd
    - references/rrse.qmd
    - references/rsq.qmd
    - references/setNumberThreads.qmd
    - references/setUseOpenMP.qmd
    - references/smape.qmd
    - references/specificity.qmd
    - references/zerooneloss.qmd
    number-sections: false
  - references.qmd
bibliography: references.bib
format:
  html:
    theme:
      light:
      - cosmo
      - theme-light.scss
      dark:
      - slate
      - theme-dark.scss
  pdf:
    documentclass: scrreprt
highlight-style: github
execute:
  freeze: auto
  cache: true
