# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Accuracy
#'
#'
#' @param actual placeholder
#' @param predicted placeholder
#'
#'
#' @export
accuracy <- function(actual, predicted) {
    .Call(`_SLmetrics_accuracy`, actual, predicted)
}

#' Zero One Loss
#'
#' @param actual placeholder
#' @param predicted placeholder
#'
#' @export
zerooneloss <- function(actual, predicted) {
    .Call(`_SLmetrics_zerooneloss`, actual, predicted)
}

#' Binary Cross Entropy
#'
#' @param actual placeholder
#' @param response placeholder
#'
entropy <- function(actual, response) {
    .Call(`_SLmetrics_entropy`, actual, response)
}

#' Huber Loss
#'
#' Calculate the huber loss of two <[numeric]> vectors.
#'
#' @param actual A <[numeric]>-vector of length N.
#' @param predicted A <[numeric]>-vector of length N.
#' @param delta A <[numeric]>-vector of length 1. 1 by default.
#'
#' @returns A <[numeric]>-value of length 1.
huberloss <- function(actual, predicted, delta = 1) {
    .Call(`_SLmetrics_huberloss`, actual, predicted, delta)
}

#' Mean Absolute Error (MAE)
#'
#' Calculate the MAE of two <[numeric]>-vectors
#'
#' @param actual A <[numeric]>-vector of length N.
#' @param predicted A <[numeric]>-vector of length N.
#'
#' @returns A <[numeric]>-value of length 1.
#'
#' @export
mae <- function(actual, predicted) {
    .Call(`_SLmetrics_mae`, actual, predicted)
}

#' Mean Square Error (MSE)
#'
#' Calculate the MSE of two <[numeric]>-vectors
#'
#' @param actual A <[numeric]>-vector of length N.
#' @param predicted A <[numeric]>-vector of length N.
#'
#' @returns A <[numeric]>-value of length 1.
#'
#' @export
mse <- function(actual, predicted) {
    .Call(`_SLmetrics_mse`, actual, predicted)
}

#' Root Mean Square Error (RMSE)
#'
#' Calculate the RMSE of two <[numeric]>-vectors
#'
#' @param actual A <[numeric]>-vector of length N.
#' @param predicted A <[numeric]>-vector of length N.
#'
#' @returns A <[numeric]>-value of length 1.
#'
#' @export
rmse <- function(actual, predicted) {
    .Call(`_SLmetrics_rmse`, actual, predicted)
}

#' Root Mean Square Logarithmic Error (RMSLE)
#'
#' Calculate the RMSLE of two <[numeric]>-vectors
#'
#' @param actual A <[numeric]>-vector of length N.
#' @param predicted A <[numeric]>-vector of length N.
#'
#' @returns A <[numeric]>-value of length 1.
#'
#' @export
rmsle <- function(actual, predicted) {
    .Call(`_SLmetrics_rmsle`, actual, predicted)
}

#' R squared
#'
#' Calculate the R squared of two <[numeric]> vectors.
#'
#' @param actual A <[numeric]>-vector of length N.
#' @param predicted A <[numeric]>-vector of length N.
#' @param k A <[numeric]>-vector of length 1. 0 by default. If k>0
#' the function returns the adjusted R squared.
#'
#' @returns A <[numeric]>-value of length 1.
rsq <- function(actual, predicted, k = 0) {
    .Call(`_SLmetrics_rsq`, actual, predicted, k)
}

#' Weighted Mean Square Error (WMSE)
#'
#' Calculate the weighted MSE of two <[numeric]>-vectors
#'
#' @param actual A <[numeric]>-vector of length N.
#' @param predicted A <[numeric]>-vector of length N.
#' @param w A <[numeric]>-vector of length N with sample weights.
#'
#' @returns A <[numeric]>-value of length 1.
#'
#' @export
wmse <- function(actual, predicted, w) {
    .Call(`_SLmetrics_wmse`, actual, predicted, w)
}

#' Weighted Root Mean Square Error (WRMSE)
#'
#' Calculate the weighted RMSE of two <[numeric]>-vectors
#'
#' @param actual A <[numeric]>-vector of length N.
#' @param predicted A <[numeric]>-vector of length N.
#' @param w A <[numeric]>-vector of length N with sample weights.
#'
#' @returns A <[numeric]>-value of length 1.
#'
#' @export
wrmse <- function(actual, predicted, w) {
    .Call(`_SLmetrics_wrmse`, actual, predicted, w)
}

