# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @templateVar .TITLE accuracy
#' @templateVar .FUN accuracy
#' @templateVar .METHOD factor
#' @template classification_factor_example
#' @template classification_cmatrix_inherit
#'
#' @export
accuracy.factor <- function(actual, predicted, ...) {
    .Call(`_SLmetrics_accuracy`, actual, predicted)
}

#' @templateVar .TITLE accuracy
#' @templateVar .FUN weighted.accuracy
#' @templateVar .METHOD factor
#' @template classification_factor_weighted_example
#' @template classification_cmatrix_inherit
#'
#' @export
weighted.accuracy.factor <- function(actual, predicted, w, ...) {
    .Call(`_SLmetrics_weighted_accuracy`, actual, predicted, w)
}

#' @templateVar .TITLE accuracy
#' @templateVar .FUN accuracy
#' @templateVar .METHOD cmatrix
#' @template classification_cmatrix_example
#' @template classification_cmatrix_inherit
#'
#' @export
accuracy.cmatrix <- function(x, ...) {
    .Call(`_SLmetrics_cmatrix_accuracy`, x)
}

#' @templateVar .TITLE baccuracy
#' @templateVar .FUN baccuracy
#' @templateVar .METHOD factor
#' @template classification_factor_example
#' @template classification_cmatrix_inherit
#'
#' @param adjust A [logical] value (default: [FALSE]). If [TRUE] the metric is adjusted for random chance \eqn{\frac{1}{k}}.
#'
#' @export
baccuracy.factor <- function(actual, predicted, adjust = FALSE, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_balanced_accuracy`, actual, predicted, adjust, na_rm = na.rm)
}

#' @templateVar .TITLE baccuracy
#' @templateVar .FUN weighted.baccuracy
#' @templateVar .METHOD factor
#' @template classification_factor_weighted_example
#' @template classification_cmatrix_inherit
#'
#' @param adjust A [logical] value (default: [FALSE]). If [TRUE] the metric is adjusted for random chance \eqn{\frac{1}{k}}.
#'
#' @export
weighted.baccuracy.factor <- function(actual, predicted, w, adjust = FALSE, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_weighted_balanced_accuracy`, actual, predicted, w, adjust, na_rm = na.rm)
}

#' @templateVar .TITLE baccuracy
#' @templateVar .FUN baccuracy
#' @templateVar .METHOD cmatrix
#' @template classification_cmatrix_example
#' @template classification_cmatrix_inherit
#'
#' @param adjust A [logical] value (default: [FALSE]). If [TRUE] the metric is adjusted for random chance \eqn{\frac{1}{k}}.
#'
#' @export
baccuracy.cmatrix <- function(x, adjust = FALSE, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_cmatrix_balanced_accuracy`, x, adjust, na_rm = na.rm)
}

#' @templateVar .TITLE ckappa
#' @templateVar .FUN ckappa
#' @templateVar .METHOD factor
#' @template classification_factor_example
#' @template classification_cmatrix_inherit
#'
#' @param beta A <[numeric]> value of [length] 1 (default: 0). If \eqn{\beta \neq 0} the off-diagonals of the confusion matrix are penalized with a factor of \eqn{(y_{+} - y_{i,-})^\beta}.
#'
#'
#' @export
ckappa.factor <- function(actual, predicted, beta = 0.0, ...) {
    .Call(`_SLmetrics_cohens_kappa`, actual, predicted, beta)
}

#' @templateVar .TITLE ckappa
#' @templateVar .FUN weighted.ckappa
#' @templateVar .METHOD factor
#' @template classification_factor_weighted_example
#' @template classification_cmatrix_inherit
#'
#' @param beta A <[numeric]> value of [length] 1 (default: 0). If \eqn{\beta \neq 0} the off-diagonals of the confusion matrix are penalized with a factor of \eqn{(y_{+} - y_{i,-})^\beta}.
#'
#' @export
weighted.ckappa.factor <- function(actual, predicted, w, beta = 0.0, ...) {
    .Call(`_SLmetrics_weighted_cohens_kappa`, actual, predicted, w, beta)
}

#' @templateVar .TITLE ckappa
#' @templateVar .FUN ckappa
#' @templateVar .METHOD cmatrix
#' @template classification_cmatrix_example
#' @template classification_cmatrix_inherit
#'
#' @param beta A <[numeric]> value of [length] 1 (default: 0). If \eqn{\beta \neq 0} the off-diagonals of the confusion matrix are penalized with a factor of \eqn{(y_{+} - y_{i,-})^\beta}.
#'
#' @export
ckappa.cmatrix <- function(x, beta = 0.0, ...) {
    .Call(`_SLmetrics_cmatrix_cohens_kappa`, x, beta)
}

#' @rdname cmatrix
#' @method cmatrix factor
#' @export
cmatrix.factor <- function(actual, predicted, ...) {
    .Call(`_SLmetrics_confusion_matrix`, actual, predicted)
}

#' @rdname cmatrix
#' @method weighted.cmatrix factor
#' @export
weighted.cmatrix.factor <- function(actual, predicted, w, ...) {
    .Call(`_SLmetrics_weighted_confusion_matrix`, actual, predicted, w)
}

#' @templateVar .TITLE dor
#' @templateVar .FUN dor
#' @templateVar .METHOD factor
#' @template classification_factor_example
#' @template classification_cmatrix_inherit
#'
#' @export
dor.factor <- function(actual, predicted, ...) {
    .Call(`_SLmetrics_diagnostic_odds_ratio`, actual, predicted)
}

#' @templateVar .TITLE dor
#' @templateVar .FUN weighted.dor
#' @templateVar .METHOD factor
#' @template classification_factor_weighted_example
#' @template classification_cmatrix_inherit
#'
#' @export
weighted.dor.factor <- function(actual, predicted, w, ...) {
    .Call(`_SLmetrics_weighted_diagnostic_odds_ratio`, actual, predicted, w)
}

#' @templateVar .TITLE dor
#' @templateVar .FUN dor
#' @templateVar .METHOD cmatrix
#' @template classification_cmatrix_example
#' @template classification_cmatrix_inherit
#'
#' @export
dor.cmatrix <- function(x, ...) {
    .Call(`_SLmetrics_cmatrix_diagnostic_odds_ratio`, x)
}

#' @rdname entropy
#' @method entropy matrix
#' @export
entropy.matrix <- function(pk, dim = 0L, base = -1.0, ...) {
    .Call(`_SLmetrics_ShannonsEntropy`, pk, dim, base)
}

#' @rdname entropy
#' @method relative.entropy matrix
#' @export
relative.entropy.matrix <- function(pk, qk, dim = 0L, base = -1.0, ...) {
    .Call(`_SLmetrics_RelativeEntropy`, pk, qk, dim, base)
}

#' @rdname entropy
#' @method cross.entropy matrix
#' @export
cross.entropy.matrix <- function(pk, qk, dim = 0L, base = -1.0, ...) {
    .Call(`_SLmetrics_CrossEntropy`, pk, qk, dim, base)
}

#' @templateVar .TITLE fbeta
#' @templateVar .FUN fbeta
#' @templateVar .METHOD factor
#' @template classification_factor_example
#' @template classification_cmatrix_inherit
#'
#' @param beta A <[numeric]> vector of [length] \eqn{1} (default: \eqn{1}).
#'
#' @export
fbeta.factor <- function(actual, predicted, beta = 1.0, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_fbeta_score`, actual, predicted, beta, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE fbeta
#' @templateVar .FUN weighted.fbeta
#' @templateVar .METHOD factor
#' @template classification_factor_weighted_example
#' @template classification_cmatrix_inherit
#'
#' @param beta A <[numeric]> vector of [length] \eqn{1} (default: \eqn{1}).
#'
#' @export
weighted.fbeta.factor <- function(actual, predicted, w, beta = 1.0, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_weighted_fbeta_score`, actual, predicted, w, beta, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE fbeta
#' @templateVar .FUN fbeta
#' @templateVar .METHOD cmatrix
#' @template classification_cmatrix_example
#' @template classification_cmatrix_inherit
#'
#' @param beta A <[numeric]> vector of [length] \eqn{1} (default: \eqn{1}).
#'
#' @export
fbeta.cmatrix <- function(x, beta = 1.0, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_cmatrix_fbeta_score`, x, beta, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE fdr
#' @templateVar .FUN fdr
#' @templateVar .METHOD factor
#' @template classification_factor_example
#' @template classification_cmatrix_inherit
#'
#' @export
fdr.factor <- function(actual, predicted, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_false_discovery_rate`, actual, predicted, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE fdr
#' @templateVar .FUN weighted.fdr
#' @templateVar .METHOD factor
#' @template classification_factor_weighted_example
#' @template classification_cmatrix_inherit
#'
#' @export
weighted.fdr.factor <- function(actual, predicted, w, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_weighted_false_discovery_rate`, actual, predicted, w, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE fdr
#' @templateVar .FUN fdr
#' @templateVar .METHOD cmatrix
#' @template classification_cmatrix_example
#' @template classification_cmatrix_inherit
#'
#' @export
fdr.cmatrix <- function(x, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_cmatrix_false_discovery_rate`, x, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE fer
#' @templateVar .FUN fer
#' @templateVar .METHOD factor
#' @template classification_factor_example
#' @template classification_cmatrix_inherit
#'
#' @export
fer.factor <- function(actual, predicted, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_false_omission_rate`, actual, predicted, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE fer
#' @templateVar .FUN weighted.fer
#' @templateVar .METHOD factor
#' @template classification_factor_weighted_example
#' @template classification_cmatrix_inherit
#'
#' @export
weighted.fer.factor <- function(actual, predicted, w, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_weighted_false_omission_rate`, actual, predicted, w, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE fer
#' @templateVar .FUN fer
#' @templateVar .METHOD cmatrix
#' @template classification_cmatrix_example
#' @template classification_cmatrix_inherit
#'
#' @export
fer.cmatrix <- function(x, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_cmatrix_false_omission_rate`, x, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE False Positive Rate
#' @templateVar .FUN fpr
#' @templateVar .METHOD factor
#' @template classification_factor_example
#' @template classification_cmatrix_inherit
#'
#' @export
fpr.factor <- function(actual, predicted, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_false_positive_rate`, actual, predicted, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE False Positive Rate
#' @templateVar .FUN weighted.fpr
#' @templateVar .METHOD factor
#' @template classification_factor_weighted_example
#' @template classification_cmatrix_inherit
#'
#' @export
weighted.fpr.factor <- function(actual, predicted, w, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_weighted_false_positive_rate`, actual, predicted, w, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE False Positive Rate
#' @templateVar .FUN fpr
#' @templateVar .METHOD cmatrix
#' @template classification_cmatrix_example
#' @template classification_cmatrix_inherit
#'
#' @export
fpr.cmatrix <- function(x, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_cmatrix_false_positive_rate`, x, estimator, na_rm = na.rm)
}

#' @method fallout factor
#' @export
fallout.factor <- function(actual, predicted, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_fallout`, actual, predicted, estimator, na_rm = na.rm)
}

#' @method weighted.fallout factor
#' @export
weighted.fallout.factor <- function(actual, predicted, w, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_weighted_fallout`, actual, predicted, w, estimator, na_rm = na.rm)
}

#' @method fallout cmatrix
#' @export
fallout.cmatrix <- function(x, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_cmatrix_fallout`, x, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE fmi
#' @templateVar .FUN fmi
#' @templateVar .METHOD factor
#' @template classification_factor_example
#' @template classification_cmatrix_inherit
#'
#' @export
fmi.factor <- function(actual, predicted, ...) {
    .Call(`_SLmetrics_fowlkes_mallows_index`, actual, predicted)
}

#' @templateVar .TITLE fmi
#' @templateVar .FUN weighted.fmi
#' @templateVar .METHOD factor
#' @template classification_factor_weighted_example
#' @template classification_cmatrix_inherit
#'
#' @export
weighted.fmi.factor <- function(actual, predicted, w, ...) {
    .Call(`_SLmetrics_weighted_fowlkes_mallows_index`, actual, predicted, w)
}

#' @templateVar .TITLE fmi
#' @templateVar .FUN fmi
#' @templateVar .METHOD cmatrix
#' @template classification_cmatrix_example
#' @template classification_cmatrix_inherit
#'
#' @export
fmi.cmatrix <- function(x, ...) {
    .Call(`_SLmetrics_cmatrix_fowlkes_mallows_index`, x)
}

#' @templateVar .TITLE hammingloss
#' @templateVar .FUN hammingloss
#' @templateVar .METHOD factor
#' @template classification_factor_example
#' @template classification_cmatrix_inherit
#'
#' @export
hammingloss.factor <- function(actual, predicted, ...) {
    .Call(`_SLmetrics_hamming_loss`, actual, predicted)
}

#' @templateVar .TITLE hammingloss
#' @templateVar .FUN weighted.hammingloss
#' @templateVar .METHOD factor
#' @template classification_factor_weighted_example
#' @template classification_cmatrix_inherit
#'
#' @export
weighted.hammingloss.factor <- function(actual, predicted, w, ...) {
    .Call(`_SLmetrics_weighted_hamming_loss`, actual, predicted, w)
}

#' @templateVar .TITLE hammingloss
#' @templateVar .FUN hammingloss
#' @templateVar .METHOD cmatrix
#' @template classification_cmatrix_example
#' @template classification_cmatrix_inherit
#'
#' @export
hammingloss.cmatrix <- function(x, ...) {
    .Call(`_SLmetrics_cmatrix_hamming_loss`, x)
}

#' @templateVar .TITLE jaccard
#' @templateVar .FUN jaccard
#' @templateVar .METHOD factor
#' @template classification_factor_example
#' @template classification_cmatrix_inherit
#'
#' @export
jaccard.factor <- function(actual, predicted, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_jaccard_score`, actual, predicted, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE jaccard
#' @templateVar .FUN weighted.jaccard
#' @templateVar .METHOD factor
#' @template classification_factor_weighted_example
#' @template classification_cmatrix_inherit
#'
#' @export
weighted.jaccard.factor <- function(actual, predicted, w, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_weighted_jaccard_score`, actual, predicted, w, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE jaccard
#' @templateVar .FUN jaccard
#' @templateVar .METHOD cmatrix
#' @template classification_cmatrix_example
#' @template classification_cmatrix_inherit
#'
#' @export
jaccard.cmatrix <- function(x, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_cmatrix_jaccard_score`, x, estimator, na_rm = na.rm)
}

#' @method csi factor
#' @export
csi.factor <- function(actual, predicted, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_critical_success_index`, actual, predicted, estimator, na_rm = na.rm)
}

#' @method weighted.csi factor
#' @export
weighted.csi.factor <- function(actual, predicted, w, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_weighted_critical_success_index`, actual, predicted, w, estimator, na_rm = na.rm)
}

#' @method csi cmatrix
#' @export
csi.cmatrix <- function(x, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_cmatrix_critical_success_index`, x, estimator, na_rm = na.rm)
}

#' @method tscore factor
#' @export
tscore.factor <- function(actual, predicted, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_threat_score`, actual, predicted, estimator, na_rm = na.rm)
}

#' @method weighted.tscore factor
#' @export
weighted.tscore.factor <- function(actual, predicted, w, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_weighted_threat_score`, actual, predicted, w, estimator, na_rm = na.rm)
}

#' @method tscore cmatrix
#' @export
tscore.cmatrix <- function(x, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_cmatrix_threat_score`, x, estimator, na_rm = na.rm)
}

#' @rdname logloss
#' @method logloss factor
#' @export
logloss.factor <- function(actual, response, normalize = TRUE, ...) {
    .Call(`_SLmetrics_LogLoss`, actual, response, normalize)
}

#' @rdname logloss
#' @method weighted.logloss factor
#' @export
weighted.logloss.factor <- function(actual, response, w, normalize = TRUE, ...) {
    .Call(`_SLmetrics_weighted_LogLoss`, actual, response, w, normalize)
}

#' @templateVar .TITLE mcc
#' @templateVar .FUN mcc
#' @templateVar .METHOD factor
#' @template classification_factor_example
#' @template classification_cmatrix_inherit
#'
#' @export
mcc.factor <- function(actual, predicted, ...) {
    .Call(`_SLmetrics_mcc`, actual, predicted)
}

#' @templateVar .TITLE mcc
#' @templateVar .FUN weighted.mcc
#' @templateVar .METHOD factor
#' @template classification_factor_weighted_example
#' @template classification_cmatrix_inherit
#'
#' @export
weighted.mcc.factor <- function(actual, predicted, w, ...) {
    .Call(`_SLmetrics_weighted_mcc`, actual, predicted, w)
}

#' @templateVar .TITLE mcc
#' @templateVar .FUN mcc
#' @templateVar .METHOD cmatrix
#' @template classification_cmatrix_example
#' @template classification_cmatrix_inherit
#'
#' @export
mcc.cmatrix <- function(x, ...) {
    .Call(`_SLmetrics_cmatrix_mcc`, x)
}

#' @method phi factor
#' @export
phi.factor <- function(actual, predicted, ...) {
    .Call(`_SLmetrics_phi_coefficient`, actual, predicted)
}

#' @method weighted.phi factor
#' @export
weighted.phi.factor <- function(actual, predicted, w, ...) {
    .Call(`_SLmetrics_weighted_phi_coefficient`, actual, predicted, w)
}

#' @method phi cmatrix
#' @export
phi.cmatrix <- function(x, ...) {
    .Call(`_SLmetrics_cmatrix_phi_coefficient`, x)
}

#' @templateVar .TITLE nlr
#' @templateVar .FUN nlr
#' @templateVar .METHOD factor
#' @template classification_factor_example
#' @template classification_cmatrix_inherit
#'
#' @export
nlr.factor <- function(actual, predicted, ...) {
    .Call(`_SLmetrics_negative_likelihood_ratio`, actual, predicted)
}

#' @templateVar .TITLE nlr
#' @templateVar .FUN weighted.nlr
#' @templateVar .METHOD factor
#' @template classification_factor_weighted_example
#' @template classification_cmatrix_inherit
#'
#' @export
weighted.nlr.factor <- function(actual, predicted, w, ...) {
    .Call(`_SLmetrics_weighted_negative_likelihood_ratio`, actual, predicted, w)
}

#' @templateVar .TITLE nlr
#' @templateVar .FUN nlr
#' @templateVar .METHOD cmatrix
#' @template classification_cmatrix_example
#' @template classification_cmatrix_inherit
#'
#' @export
nlr.cmatrix <- function(x, ...) {
    .Call(`_SLmetrics_cmatrix_negative_likelihood_ratio`, x)
}

#' @templateVar .TITLE npv
#' @templateVar .FUN npv
#' @templateVar .METHOD factor
#' @template classification_factor_example
#' @template classification_cmatrix_inherit
#'
#' @export
npv.factor <- function(actual, predicted, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_negative_predictive_value`, actual, predicted, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE npv
#' @templateVar .FUN weighted.npv
#' @templateVar .METHOD factor
#' @template classification_factor_weighted_example
#' @template classification_cmatrix_inherit
#'
#' @export
weighted.npv.factor <- function(actual, predicted, w, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_weighted_negative_predictive_value`, actual, predicted, w, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE npv
#' @templateVar .FUN npv
#' @templateVar .METHOD cmatrix
#' @template classification_cmatrix_example
#' @template classification_cmatrix_inherit
#'
#' @export
npv.cmatrix <- function(x, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_cmatrix_negative_predictive_value`, x, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE plr
#' @templateVar .FUN plr
#' @templateVar .METHOD factor
#' @template classification_factor_example
#' @template classification_cmatrix_inherit
#'
#' @export
plr.factor <- function(actual, predicted, ...) {
    .Call(`_SLmetrics_positive_likelihood_ratio`, actual, predicted)
}

#' @templateVar .TITLE plr
#' @templateVar .FUN weighted.plr
#' @templateVar .METHOD factor
#' @template classification_factor_weighted_example
#' @template classification_cmatrix_inherit
#'
#' @export
weighted.plr.factor <- function(actual, predicted, w, ...) {
    .Call(`_SLmetrics_weighted_positive_likelihood_ratio`, actual, predicted, w)
}

#' @templateVar .TITLE plr
#' @templateVar .FUN plr
#' @templateVar .METHOD cmatrix
#' @template classification_cmatrix_example
#' @template classification_cmatrix_inherit
#'
#' @export
plr.cmatrix <- function(x, ...) {
    .Call(`_SLmetrics_cmatrix_positive_likelihood_ratio`, x)
}

#' @templateVar .TITLE precision
#' @templateVar .FUN precision
#' @templateVar .METHOD factor
#' @template classification_factor_example
#' @template classification_cmatrix_inherit
#'
#' @export
precision.factor <- function(actual, predicted, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_precision`, actual, predicted, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE precision
#' @templateVar .FUN weighted.precision
#' @templateVar .METHOD factor
#' @template classification_factor_weighted_example
#' @template classification_cmatrix_inherit
#'
#' @export
weighted.precision.factor <- function(actual, predicted, w, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_weighted_precision`, actual, predicted, w, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE precision
#' @templateVar .FUN precision
#' @templateVar .METHOD cmatrix
#' @template classification_cmatrix_example
#' @template classification_cmatrix_inherit
#'
#' @export
precision.cmatrix <- function(x, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_cmatrix_precision`, x, estimator, na_rm = na.rm)
}

#' @method ppv factor
#' @export
ppv.factor <- function(actual, predicted, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_ppv`, actual, predicted, estimator, na_rm = na.rm)
}

#' @method weighted.ppv factor
#' @export
weighted.ppv.factor <- function(actual, predicted, w, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_weighted_ppv_score`, actual, predicted, w, estimator, na_rm = na.rm)
}

#' @method ppv cmatrix
#' @export
ppv.cmatrix <- function(x, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_cmatrix_ppv_score`, x, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE Receiver Operator Characteristics Curve
#' @templateVar .FUN pr.curve
#' @templateVar .TYPE roc
#' @templateVar .METHOD factor
#' @template classification_auc_inherit
#'
#' @export
pr.curve.factor <- function(actual, response, thresholds = NULL, presorted = FALSE, ...) {
    .Call(`_SLmetrics_precision_recall_curve`, actual, response, thresholds, presorted)
}

#' @templateVar .TITLE Receiver Operator Characteristics Curve
#' @templateVar .FUN weighted.pr.curve
#' @templateVar .TYPE roc
#' @templateVar .METHOD factor
#' @template classification_auc_inherit
#'
#' @export
weighted.pr.curve.factor <- function(actual, response, w, thresholds = NULL, presorted = FALSE, ...) {
    .Call(`_SLmetrics_weighted_precision_recall_curve`, actual, response, w, thresholds, presorted)
}

#' @templateVar .TITLE Area under the Precision-Recall Curve
#' @templateVar .FUN auc.pr.curve
#' @templateVar .TYPE auc
#' @templateVar .METHOD factor
#' @template classification_auc_inherit
#'
#' @rawNamespace S3method(auc.pr.curve,factor)
auc.pr.curve.factor <- function(actual, response, micro = NULL, method = 0L, ...) {
    .Call(`_SLmetrics_precision_recall_auc`, actual, response, micro, method)
}

#' @templateVar .TITLE Area under the Precision-Recall Curve
#' @templateVar .FUN weighted.auc.pr.curve
#' @templateVar .TYPE auc
#' @templateVar .METHOD factor
#' @template classification_auc_inherit
#'
#' @rawNamespace S3method(weighted.auc.pr.curve,factor)
weighted.auc.pr.curve.factor <- function(actual, response, w, micro = NULL, method = 0L, ...) {
    .Call(`_SLmetrics_precision_recall_auc_weighted`, actual, response, w, micro, method)
}

#' @templateVar .TITLE recall
#' @templateVar .FUN recall
#' @templateVar .METHOD factor
#' @template classification_factor_example
#' @template classification_cmatrix_inherit
#'
#' @export
recall.factor <- function(actual, predicted, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_recall_score`, actual, predicted, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE recall
#' @templateVar .FUN weighted.recall
#' @templateVar .METHOD factor
#' @template classification_factor_weighted_example
#' @template classification_cmatrix_inherit
#'
#' @export
weighted.recall.factor <- function(actual, predicted, w, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_weighted_recall_score`, actual, predicted, w, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE recall
#' @templateVar .FUN recall
#' @templateVar .METHOD cmatrix
#' @template classification_cmatrix_example
#' @template classification_cmatrix_inherit
#'
#' @export
recall.cmatrix <- function(x, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_cmatrix_recall_score`, x, estimator, na_rm = na.rm)
}

#' @method sensitivity factor
#' @export
sensitivity.factor <- function(actual, predicted, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_sensitivity_score`, actual, predicted, estimator, na_rm = na.rm)
}

#' @method weighted.sensitivity factor
#' @export
weighted.sensitivity.factor <- function(actual, predicted, w, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_weighted_sensitivity_score`, actual, predicted, w, estimator, na_rm = na.rm)
}

#' @method sensitivity cmatrix
#' @export
sensitivity.cmatrix <- function(x, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_cmatrix_sensitivity_score`, x, estimator, na_rm = na.rm)
}

#' @method tpr factor
#' @export
tpr.factor <- function(actual, predicted, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_true_positive_rate`, actual, predicted, estimator, na_rm = na.rm)
}

#' @method weighted.tpr factor
#' @export
weighted.tpr.factor <- function(actual, predicted, w, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_weighted_true_positive_rate`, actual, predicted, w, estimator, na_rm = na.rm)
}

#' @method tpr cmatrix
#' @export
tpr.cmatrix <- function(x, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_cmatrix_true_positive_rate`, x, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE Receiver Operator Characteristics Curve
#' @templateVar .FUN roc.curve
#' @templateVar .TYPE roc.curve
#' @templateVar .METHOD factor
#' @template classification_auc_inherit
#'
#' @export
roc.curve.factor <- function(actual, response, thresholds = NULL, presorted = FALSE, ...) {
    .Call(`_SLmetrics_roc_curve_unweighted`, actual, response, thresholds, presorted)
}

#' @templateVar .TITLE Receiver Operator Characteristics Curve
#' @templateVar .FUN weighted.roc.curve
#' @templateVar .TYPE roc.curve
#' @templateVar .METHOD factor
#' @template classification_auc_inherit
#'
#' @export
weighted.roc.curve.factor <- function(actual, response, w, thresholds = NULL, presorted = FALSE, ...) {
    .Call(`_SLmetrics_roc_curve_weighted`, actual, response, w, thresholds, presorted)
}

#' @templateVar .TITLE Area under the ROC curve
#' @templateVar .FUN auc.roc.curve
#' @templateVar .TYPE auc
#' @templateVar .METHOD factor
#' @template classification_auc_inherit
#'
#' @export
auc.roc.curve.factor <- function(actual, response, micro = NULL, method = 0L, ...) {
    .Call(`_SLmetrics_roc_auc`, actual, response, micro, method)
}

#' @templateVar .TITLE Area under the ROC curve
#' @templateVar .FUN weighted.auc.roc.curve
#' @templateVar .TYPE auc
#' @templateVar .METHOD factor
#' @template classification_auc_inherit
#'
#' @export
weighted.auc.roc.curve.factor <- function(actual, response, w, micro = NULL, method = 0L, ...) {
    .Call(`_SLmetrics_roc_auc_weighted`, actual, response, w, micro, method)
}

#' @templateVar .TITLE specificity
#' @templateVar .FUN specificity
#' @templateVar .METHOD factor
#' @template classification_factor_example
#' @template classification_cmatrix_inherit
#'
#' @export
specificity.factor <- function(actual, predicted, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_specificity`, actual, predicted, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE specificity
#' @templateVar .FUN weighted.specificity
#' @templateVar .METHOD factor
#' @template classification_factor_weighted_example
#' @template classification_cmatrix_inherit
#'
#' @export
weighted.specificity.factor <- function(actual, predicted, w, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_weighted_specificity`, actual, predicted, w, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE specificity
#' @templateVar .FUN specificity
#' @templateVar .METHOD cmatrix
#' @template classification_cmatrix_example
#' @template classification_cmatrix_inherit
#'
#' @export
specificity.cmatrix <- function(x, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_cmatrix_specificity`, x, estimator, na_rm = na.rm)
}

#' @method tnr factor
#' @export
tnr.factor <- function(actual, predicted, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_true_negative_rate`, actual, predicted, estimator, na_rm = na.rm)
}

#' @method weighted.tnr factor
#' @export
weighted.tnr.factor <- function(actual, predicted, w, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_weighted_true_negative_rate`, actual, predicted, w, estimator, na_rm = na.rm)
}

#' @method tnr cmatrix
#' @export
tnr.cmatrix <- function(x, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_cmatrix_true_negative_rate`, x, estimator, na_rm = na.rm)
}

#' @method selectivity factor
#' @export
selectivity.factor <- function(actual, predicted, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_selectivity`, actual, predicted, estimator, na_rm = na.rm)
}

#' @method weighted.selectivity factor
#' @export
weighted.selectivity.factor <- function(actual, predicted, w, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_weighted_selectivity`, actual, predicted, w, estimator, na_rm = na.rm)
}

#' @method selectivity cmatrix
#' @export
selectivity.cmatrix <- function(x, estimator = 0L, na.rm = TRUE, ...) {
    .Call(`_SLmetrics_cmatrix_selectivity`, x, estimator, na_rm = na.rm)
}

#' @templateVar .TITLE zerooneloss
#' @templateVar .FUN zerooneloss
#' @templateVar .METHOD factor
#' @template classification_factor_example
#' @template classification_cmatrix_inherit
#'
#' @export
zerooneloss.factor <- function(actual, predicted, ...) {
    .Call(`_SLmetrics_zero_one_loss`, actual, predicted)
}

#' @templateVar .TITLE zerooneloss
#' @templateVar .FUN weighted.zerooneloss
#' @templateVar .METHOD factor
#' @template classification_factor_weighted_example
#' @template classification_cmatrix_inherit
#'
#' @export
weighted.zerooneloss.factor <- function(actual, predicted, w, ...) {
    .Call(`_SLmetrics_weighted_zero_one_loss`, actual, predicted, w)
}

#' @templateVar .TITLE zerooneloss
#' @templateVar .FUN zerooneloss
#' @templateVar .METHOD cmatrix
#' @template classification_cmatrix_example
#' @template classification_cmatrix_inherit
#'
#' @export
zerooneloss.cmatrix <- function(x, ...) {
    .Call(`_SLmetrics_cmatrix_zero_one_loss`, x)
}

#' @rdname logloss
#' @method logloss integer
#' @export
logloss.integer <- function(actual, response, normalize = TRUE, ...) {
    .Call(`_SLmetrics_PoissonLogLoss`, actual, response, normalize)
}

#' @rdname logloss
#' @method weighted.logloss integer
#' @export
weighted.logloss.integer <- function(actual, response, w, normalize = TRUE, ...) {
    .Call(`_SLmetrics_weighted_PoissonLogLoss`, actual, response, w, normalize)
}

#' @rdname rsq
#' @method rsq numeric
#' @export
rsq.numeric <- function(actual, predicted, k = 0.0, ...) {
    .Call(`_SLmetrics_rsq`, actual, predicted, k)
}

#' @rdname rsq
#' @method weighted.rsq numeric
#' @export
weighted.rsq.numeric <- function(actual, predicted, w, k = 0.0, ...) {
    .Call(`_SLmetrics_weighted_rsq`, actual, predicted, w, k)
}

#' @rdname ccc
#' @method ccc numeric
#' @export
ccc.numeric <- function(actual, predicted, correction = FALSE, ...) {
    .Call(`_SLmetrics_ccc`, actual, predicted, correction)
}

#' @rdname ccc
#' @method weighted.ccc numeric
#' @export
weighted.ccc.numeric <- function(actual, predicted, w, correction = FALSE, ...) {
    .Call(`_SLmetrics_weighted_ccc`, actual, predicted, w, correction)
}

#' @rdname huberloss
#' @method huberloss numeric
#' @export
huberloss.numeric <- function(actual, predicted, delta = 1.0, ...) {
    .Call(`_SLmetrics_huberloss`, actual, predicted, delta)
}

#' @rdname huberloss
#' @method weighted.huberloss numeric
#' @export
weighted.huberloss.numeric <- function(actual, predicted, w, delta = 1.0, ...) {
    .Call(`_SLmetrics_weighted_huberloss`, actual, predicted, w, delta)
}

#' @rdname mae
#' @method mae numeric
#' @export
mae.numeric <- function(actual, predicted, ...) {
    .Call(`_SLmetrics_mae`, actual, predicted)
}

#' @rdname mae
#' @method weighted.mae numeric
#' @export
weighted.mae.numeric <- function(actual, predicted, w, ...) {
    .Call(`_SLmetrics_weighted_mae`, actual, predicted, w)
}

#' @rdname mape
#' @method mape numeric
#' @export
mape.numeric <- function(actual, predicted, ...) {
    .Call(`_SLmetrics_mape`, actual, predicted)
}

#' @rdname mape
#' @method weighted.mape numeric
#' @export
weighted.mape.numeric <- function(actual, predicted, w, ...) {
    .Call(`_SLmetrics_weighted_mape`, actual, predicted, w)
}

#' @rdname mpe
#' @method mpe numeric
#' @export
mpe.numeric <- function(actual, predicted, ...) {
    .Call(`_SLmetrics_mpe`, actual, predicted)
}

#' @rdname mpe
#' @method weighted.mpe numeric
#' @export
weighted.mpe.numeric <- function(actual, predicted, w, ...) {
    .Call(`_SLmetrics_weighted_mpe`, actual, predicted, w)
}

#' @rdname mse
#' @method mse numeric
#' @export
mse.numeric <- function(actual, predicted, ...) {
    .Call(`_SLmetrics_mse`, actual, predicted)
}

#' @rdname mse
#' @method weighted.mse numeric
#' @export
weighted.mse.numeric <- function(actual, predicted, w, ...) {
    .Call(`_SLmetrics_weighted_mse`, actual, predicted, w)
}

#' @rdname pinball
#' @method pinball numeric
#' @export
pinball.numeric <- function(actual, predicted, alpha = 0.5, deviance = FALSE, ...) {
    .Call(`_SLmetrics_pinball`, actual, predicted, alpha, deviance)
}

#' @rdname pinball
#' @method weighted.pinball numeric
#' @export
weighted.pinball.numeric <- function(actual, predicted, w, alpha = 0.5, deviance = FALSE, ...) {
    .Call(`_SLmetrics_weighted_pinball`, actual, predicted, w, alpha, deviance)
}

#' @rdname rae
#' @method rae numeric
#' @export
rae.numeric <- function(actual, predicted, ...) {
    .Call(`_SLmetrics_rae`, actual, predicted)
}

#' @rdname rae
#' @method weighted.rae numeric
#' @export
weighted.rae.numeric <- function(actual, predicted, w, ...) {
    .Call(`_SLmetrics_weighted_rae`, actual, predicted, w)
}

#' @rdname rrmse
#' @method rrmse numeric
#' @export
rrmse.numeric <- function(actual, predicted, normalization = 1L, ...) {
    .Call(`_SLmetrics_RelativeRootMeanSquaredError`, actual, predicted, normalization)
}

#' @rdname rrmse
#' @method weighted.rrmse numeric
#' @export
weighted.rrmse.numeric <- function(actual, predicted, w, normalization = 1L, ...) {
    .Call(`_SLmetrics_weighted_RelativeRootMeanSquaredError`, actual, predicted, w, normalization)
}

#' @rdname rmse
#' @method rmse numeric
#' @export
rmse.numeric <- function(actual, predicted, ...) {
    .Call(`_SLmetrics_rmse`, actual, predicted)
}

#' @rdname rmse
#' @method weighted.rmse numeric
#' @export
weighted.rmse.numeric <- function(actual, predicted, w, ...) {
    .Call(`_SLmetrics_weighted_rmse`, actual, predicted, w)
}

#' @rdname rmsle
#' @method rmsle numeric
#' @export
rmsle.numeric <- function(actual, predicted, ...) {
    .Call(`_SLmetrics_rmsle`, actual, predicted)
}

#' @rdname rmsle
#' @method weighted.rmsle numeric
#' @export
weighted.rmsle.numeric <- function(actual, predicted, w, ...) {
    .Call(`_SLmetrics_weighted_rmsle`, actual, predicted, w)
}

#' @rdname rrse
#' @method rrse numeric
#' @export
rrse.numeric <- function(actual, predicted, ...) {
    .Call(`_SLmetrics_rrse`, actual, predicted)
}

#' @rdname rrse
#' @method weighted.rrse numeric
#' @export
weighted.rrse.numeric <- function(actual, predicted, w, ...) {
    .Call(`_SLmetrics_weighted_rrse`, actual, predicted, w)
}

#' @rdname smape
#' @method smape numeric
#' @export
smape.numeric <- function(actual, predicted, ...) {
    .Call(`_SLmetrics_smape`, actual, predicted)
}

#' @rdname smape
#' @method weighted.smape numeric
#' @export
weighted.smape.numeric <- function(actual, predicted, w, ...) {
    .Call(`_SLmetrics_weighted_smape`, actual, predicted, w)
}

#' @rdname xy.auc
#' @method xy.auc numeric
#' @rawNamespace S3method(xy.auc,numeric)
xy.auc.numeric <- function(y, x, method = 0L, presorted = TRUE, ...) {
    .Call(`_SLmetrics_auc`, y, x, method, presorted)
}

#' @rdname cov.wt
#' @method cov.wt matrix
#' @export
cov.wt.matrix <- function(x, wt = NULL, cor = FALSE, center = TRUE, method = "unbiased", ...) {
    .Call(`_SLmetrics_covariance_matrix`, x, wt, cor, center, method)
}

#' @rdname cov.wt
#' @method cov.wt data.frame
#' @export
cov.wt.data.frame <- function(x, wt = NULL, cor = FALSE, center = TRUE, method = "unbiased", ...) {
    .Call(`_SLmetrics_covariance_dataframe`, x, wt, cor, center, method)
}

.openmp_available <- function() {
    .Call(`_SLmetrics_openmp_available`)
}

.enable_openmp <- function() {
    .Call(`_SLmetrics_enable_openmp`)
}

.disable_openmp <- function() {
    .Call(`_SLmetrics_disable_openmp`)
}

.available_threads <- function() {
    .Call(`_SLmetrics_available_threads`)
}

.use_threads <- function(value = -1L) {
    .Call(`_SLmetrics_use_threads`, value)
}

#' @method presort matrix
#' @export
presort.matrix <- function(x, decreasing = FALSE, ...) {
    .Call(`_SLmetrics_sort_matrix`, x, decreasing)
}

#' @method preorder matrix
#' @export
preorder.matrix <- function(x, decreasing = FALSE, ...) {
    .Call(`_SLmetrics_order_matrix`, x, decreasing)
}

