# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Mean Absolute Error (MAE)
#'
#' Calculate the MAE of two <[numeric]>-vectors
#'
#' @param actual A <[numeric]>-vector of length N.
#' @param predicted A <[numeric]>-vector of length N.
#'
#' @returns A <[numeric]>-value of length 1.
#'
#' @export
mae <- function(actual, predicted) {
    .Call(`_SLmetrics_mae`, actual, predicted)
}

#' Mean Square Error (MSE)
#'
#' Calculate the MSE of two <[numeric]>-vectors
#'
#' @param actual A <[numeric]>-vector of length N.
#' @param predicted A <[numeric]>-vector of length N.
#'
#' @returns A <[numeric]>-value of length 1.
#'
#' @export
mse <- function(actual, predicted) {
    .Call(`_SLmetrics_mse`, actual, predicted)
}

#' Root Mean Square Error (RMSE)
#'
#' Calculate the RMSE of two <[numeric]>-vectors
#'
#' @param actual A <[numeric]>-vector of length N.
#' @param predicted A <[numeric]>-vector of length N.
#'
#' @returns A <[numeric]>-value of length 1.
#'
#' @export
rmse <- function(actual, predicted) {
    .Call(`_SLmetrics_rmse`, actual, predicted)
}

#' Root Mean Square Logarithmic Error (RMSLE)
#'
#' Calculate the RMSLE of two <[numeric]>-vectors
#'
#' @param actual A <[numeric]>-vector of length N.
#' @param predicted A <[numeric]>-vector of length N.
#'
#' @returns A <[numeric]>-value of length 1.
#'
#' @export
rmsle <- function(actual, predicted) {
    .Call(`_SLmetrics_rmsle`, actual, predicted)
}

