on:
  workflow_dispatch:
  push:
    branches: [development, quarto-docs]
    paths: ['docs/**', '.github/workflows/build-docs.yml']

name: Build Docs

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true


      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
        
      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: 'always'
          packages:
            local::.
            deps::.
          extra-packages:
            any::MLmetrics
            any::mlr3measures
            any::yardstick
            any::bench
            any::tidyverse
            any::tidymodels
            
      - name: Render docs
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html 
          path: docs/
          
      - name: Publish docs
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs/
          render: false
        
