on:
  workflow_dispatch:
  push:
    paths: ['man/**','docs/**', '.github/workflows/build-docs.yaml', 'tools/doc-builders/build-yaml.py']
    branches-ignore:
      - stable
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: Build Docs

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true


      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
        
      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: 'always'
          packages:
            local::.
            deps::.
          extra-packages:
            any::MLmetrics
            any::mlr3measures
            any::yardstick
            any::bench
            any::tidyverse
            any::tidymodels
            any::stringi

      - name: Setup Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.x'
          cache: pip

      - name: "Setup Python dependencies"
        shell: bash
        run: |
          pip install -r tools/requirements.txt

      - name: Parse Roxygen files
        shell: Rscript {0}
        run: |

          # 1) create folders
          dir.create("docs/ref_regression")
          dir.create("docs/ref_classification")

          # 2) source builders
          source('tools/doc-builders/build-qmd.R')

      - name: Build YAML-file
        run: python tools/doc-builders/build-yaml.py

      - name: Render docs
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          path: docs/
          
      - name: Publish docs
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs/
          render: false
        
