on:
  workflow_dispatch:
  push:
    branches: [development, quarto-docs]

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::MLmetrics
            any::mlr3measures
            any::yardstick
            any::bench
            any::devtools
        
      - name: Install TinyTex and {SLmetrics}
        if: runner.os == 'Linux'
        run: |
          quarto install tinytex
          sudo Rscript -e "devtools::install_github(repo = 'https://github.com/serkor1/SLmetrics@*release', ref  = 'main')"
          
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
