on:
  workflow_dispatch:
  push:
    branches: [development, quarto-docs]

name: Build Docs

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
        
      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            local::.
            any::MLmetrics
            any::mlr3measures
            any::yardstick
            any::bench
            any::tidyverse
            any::tidymodels
        
      - name: Install TinyTex
        if: runner.os == 'Linux'
        run: |
          quarto install tinytex
          
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs/
        
